version: '2'
services:
  db:
    container_name: pallevar_db
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pallevar-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "$port_db:4576"
  web:
    container_name: pallevar_odoo
    image: pallevar_odoo:13
    build: ./
    depends_on:
      - db
    ports:
      - "$port:8069"
      - "$chat_port:8072"
    volumes:
      - pallevar-web-data:/var/lib/odoo
      - ./docker:/etc/odoo/
      - ./addons:/mnt/extra-addons
volumes:
    pallevar-web-data:
    pallevar-db-data: